### ISSUE TITLE
100% data driven possible

### ISSUE THREAD

**Issue by joe-getcouragenow** [cph-cachet/research.package#12]
I had a look at the code and the Data driving the example is currently hardcoded.

I need to load up the Widget and then everything is 100% driven from the JSON loaded from the Server.

Assuming you wanted the survey to be split onto 3 pages, if there a way to tell it that, and it will do the routing ?
At the end of the survey the data can then be sent back to the Server ? 

Again sorry about the non specific questions, but i am just trying to validate if i can use this lib for my use case.

**Comment by bardram** [comment]
Hi @joe-getcouragenow -- we are working on supporting this scenario. Right now I'm implementing support for json de/serialization in Research Package. This will be release as version 0.5.0 soon. We're in the same situation where we want to download a json description of a survey and instantiate it in RP.

Stay tuned.

**Comment by bardram** [comment]
Version 0.5.x have been release which supports serialization to and from json. 

See the unit test `example_json_test.dart` for examples of how this is done.
