### ISSUE TITLE
Cognitive Function Tests have 2 different proceed buttons but one is disabled - Confusing for users?

### ISSUE THREAD

**Issue by Strain-solutions** [cph-cachet/research.package#14]
As the title says, I find that the cognitive function tests have a 'READY' button in the centre of the instruction screen as well as a "NEXT" button in the footer.  However, the next button is grey and onPressed = null which has confused some of my older participants.

My fix is-- in RPUITask.dart there is a StreamBuilder as part of ' _taskPersistentFooterButtons' which returns the RaisedButton with 'NEXT' as the text widget.

I have wrapped the RaisedButton in an opacity with a turnery expression based on snapshot.data.  I've pasted the code below, but please note (1) I am an amateur coder not a CS guy, it is highly unlikely I have improved anyones code... (2) I am ONLY using the cognitive function parts of the package, this may (probably?) break something elsewhere!

Thanks
Nick

ps Thanks for such a great tool!

    `
    StreamBuilder<bool>(
              stream: blocQuestion.questionReadyToProceed,
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  return Opacity( // <<This is my addition
                      opacity: snapshot.data ? 1:0,
                      child:RaisedButton(
                    color: Theme.of(context).accentColor,
                    textColor: Colors.white,
                    child: Text(
                      RPLocalizations.of(context)?.translate('NEXT') ?? "NEXT",
                    ),
                    onPressed: snapshot.data
                        ? () {
                            blocTask.sendStatus(StepStatus.Finished);
                          }
                        : null,
                  ));
                } else {
                  return Container();
                }
              },
            ),`

**Comment by MadsVSChristensen** [comment]
As cognitive tests arent in this package ATM, I am closing this issue. However, they should be release in a separate package later.
