### ISSUE TITLE
upgrade dependency: signature to v3.2.0

### ISSUE THREAD

**Issue by ezmegy** [cph-cachet/research.package#15]
There were breaking changes in signature 3.+ 

This in itself is not a major problem but I am using Research Package currently in a project along flutter_form_builder which relies on signature 3.+, so I could not build the app before bringing Research Package's dependency to 3.+ as well...

**Comment by alexodus** [comment]
Version 3.2.0 "Added web support (export was not working in web previously)".
I need to release my flutter app also for web.

**Comment by tiloc** [comment]
To give you a heads-up, the Signature package will be upgraded by its makers in the next few days because of null-safety.

**Comment by MadsVSChristensen** [comment]
Signature has been upgraded to the latest version in release #0.6.0.
