### ISSUE TITLE
Surveys look strange in Dark Mode

### ISSUE THREAD

**Issue by bardram** [cph-cachet/research.package#18]
As shown below, the font is dark grey on black, which is hard to read. The same with the buttons, which look strange.

![pm_5](https://user-images.githubusercontent.com/1196642/100360990-e7f6b780-2ff9-11eb-8ac7-67c0ca5547c9.png)

**Comment by MadsVSChristensen** [comment]
Theming has been updated in release #0.6.0 and should be more customizable to allow the developer to change these thing using the Theme.
