### ISSUE TITLE
Does RPPredicateStepNavigationRule support multiple branching behavior?

### ISSUE THREAD

**Issue by mshukuno** [cph-cachet/research.package#19]
It seems ResearchKit's ORKPredicateStepNavigationRule supports multiple branching behaviors [see ResearchKit GitHub](https://github.com/ResearchKit/ResearchKit/issues/1006). 

Currently, RPPredicateStepNavigationRule works more like RPDirectStepNavigationRule as long as I tested. I am trying to exactly the same mentioned in the previously shared link. Does RPPredicateStepNavigationRule support multiple branching?

**Comment by MadsVSChristensen** [comment]
As of 0.7.0 `RPPredicateStepNavigationRule` has been removed.
