### ISSUE TITLE
Plans for null-safety?

### ISSUE THREAD

**Issue by tiloc** [cph-cachet/research.package#24]
First of all, let me congratulate you on this great package! It is very helpful.
I am slowly migrating towards null-safety in my overall app. Do you have plans to go null-safe? I am specifically currently struggling with the onCancel method and its result parameter. Apart from that I got the linear survey to work well embedded into an otherwise null-safe app.

**Comment by bardram** [comment]
Yes - we plan to migrate all the CACHET plugins and packages to null-safety. We have started with some of the sensing plugins, and are making our way "up the stack" as recommended by the Dart/Flutter team. Research Package will also be on null safety at some point when the underlying packages are there.

**Comment by MadsVSChristensen** [comment]
With release #0.6.0 Research Package is now Null-safe.
