### ISSUE TITLE
AnswerFormat for free text?

### ISSUE THREAD

**Issue by tiloc** [cph-cachet/research.package#26]
Is there a way to ask for a short piece of text, such as a comment? I am aware of the choice with free-text, but that only allows a single line and looks strange if this is the only choice. I am looking for an input field for maybe 5 lines of text.

**Comment by bardram** [comment]
@MadsVSChristensen -- I've mentioned the same issue - I think we should look into this.

**Comment by tiloc** [comment]
To be fair: I have worked with Research Package intensively for a while and have since converted to use FHIR Questionnaires for very similar purposes. Please feel free to look here: https://github.com/tiloc/faiadashu or here: http://www.legentix.com/faiadashu for a running example.

You might also be interested to know that this package is supporting certain elements from your Danish sundhet.dk FHIR specification.

**Comment by MadsVSChristensen** [comment]
Research Package supports free text answer format  - check RPUITextInputQuestionBody /  RPTextAnswerFormat.
