### ISSUE TITLE
Inconsistent look & feel

### ISSUE THREAD

**Issue by bardram** [cph-cachet/research.package#31]
There is a number of inconsistencies in the current version of RP in terms of look & feel. Attached are three images - the issues are:
 
 * why do the intro screen and questions have a blue background?
 * why is the "Done" screen fundamentally different in term of color and image style?

![Screenshot_20210416-150459](https://user-images.githubusercontent.com/1196642/115029104-ee60cf80-9ec5-11eb-8c70-390a45458004.jpg)
![Screenshot_20210416-150448](https://user-images.githubusercontent.com/1196642/115029132-f6207400-9ec5-11eb-8b75-8ee18964351c.jpg)
![Screenshot_20210416-150300](https://user-images.githubusercontent.com/1196642/115029145-fa4c9180-9ec5-11eb-8ed7-d67800e9ac98.jpg)

**Comment by MadsVSChristensen** [comment]
As of release 0.6.0 the color schemes have been made customizable. 
The CompletionStep (the "Done" screen) has remained in the same style but is also color and text customizable.
