### ISSUE TITLE
Several images are missing in the informed consent sections

### ISSUE THREAD

**Issue by bardram** [cph-cachet/research.package#32]
It seems like several images in the informed consent pages are missing.... Below are just a few examples that I found in the StudyApp.

![Screenshot_20210416-151353](https://user-images.githubusercontent.com/1196642/115030148-10a71d00-9ec7-11eb-9ebf-32e3aea69f62.jpg)
![Screenshot_20210416-151428](https://user-images.githubusercontent.com/1196642/115030176-17359480-9ec7-11eb-9948-b7ca04f2951f.jpg)
![Screenshot_20210416-151423](https://user-images.githubusercontent.com/1196642/115030194-1bfa4880-9ec7-11eb-8a58-9228f772be06.jpg)
![Screenshot_20210416-151417](https://user-images.githubusercontent.com/1196642/115030204-1f8dcf80-9ec7-11eb-9cb1-d5a4c914bbb6.jpg)

**Comment by MadsVSChristensen** [comment]
As of release #0.6.0 all consent sections now contain a dedicated image.
