### ISSUE TITLE
Current status of the library

### ISSUE THREAD

**Issue by jlopezr** [cph-cachet/research.package#4]
Hello!

We are evaluating the usage of flutter for a new app for medical surveys that we started developing. Is there any demo app or test for your library?

BR,

    Juan

**Comment by barnabashomola** [comment]
Hi Juan,

Thank you for your interest! We will soon release an example application with the currently available answer formats.

BR,
Barnabas

**Comment by barnabashomola** [comment]
The demo app has been added to this repo. 
You can find it in this folder: https://github.com/cph-cachet/research.package/tree/master/research_package_demo_app

We hope it gives you an introduction to the package.

BR

**Comment by jlopezr** [comment]
Great! It is a good intro to the package :)

Regarding text answer formats, is something you have in your short term roadmap? If no, what are the contributing policy? I am considering using your lib but I will definetely need the text formats. It seems that it won't be very difficult...
