### ISSUE TITLE
Cannot specify a title in RPConsentSection

### ISSUE THREAD

**Issue by bardram** [cph-cachet/research.package#48]
When creating a `RPConsentSection` the title is automatically assigned to the English version, even if another title is provided. This is an bug in the constructor which looks like this:

```
  RPConsentSection(
      {required this.type,
      String? title,
      this.summary,
      this.content,
      this.dataTypes,
      this.customIllustration}) {
    assert(type != RPConsentSectionType.Custom || title != null, "If a you are creating a Custom ConsentSection, then a title must be provided.");
    this.title = (type == RPConsentSectionType.Custom) ?
      title! : _localizedTitleForConsentSectionType(type);
  }
```

It should not call the `_localizedTitleForConsentSectionType()` method, if a (custom) title is provided.

**Comment by MadsVSChristensen** [comment]
As of release #0.6.3, RPConsentSection now takes the custom title if one is provided.
