### ISSUE TITLE
QuestionStep with TextAnswerFormat does not work in Form

### ISSUE THREAD

**Issue by jfkominsky** [cph-cachet/research.package#52]
Tried adding a QuestionStep to a Form, and the QuestionStep has a TextAnswerFormat. It shows the title text correctly in the form, but it will not render the text box or allow text entry. This is true with or without hint text. Furthermore, because it expects the text box to be required, it does not allow the user to proceed past that step.

Tested in ResearchPackage 0.6.5+1 on an AVD, API 30

**Comment by MadsVSChristensen** [comment]
Thank you for the feedback - it has been fixed in the [latest commit](https://github.com/cph-cachet/research.package/commit/60756c2f1ca74c2b36d103d52b43291416adda33) and will be part of the next release.
