### ISSUE TITLE
RPFormStep ignores single RPQuestionStep optional tags

### ISSUE THREAD

**Issue by eveetc** [cph-cachet/research.package#58]
When creating a form step with several questions included, where not all are necessary, the optional parameter is ignored in the single questions. For a example using a RPTextAnswerFormat within a FormStep for additional information, which isn't necessary to be answered and tagged as optional, still is required to be filled out, because the whole form requires it.

Is there any way to get rid of this behavior, or do I really need to put the open text input outside the form ?

**Comment by MadsVSChristensen** [comment]
Hi @eveetc, 

I will add this to the upcoming release. Thanks for letting us know! It is great to have feedback :-) 

Mads

**Comment by eveetc** [comment]
@MadsVSChristensen great! Thank you for this great package :) I am using it for the surveys in my master thesis app.

One additional suggestion I would add, if possible:
Adding an open answer field for every scale based question. 
Like it's handled inside google forms:

![image](https://user-images.githubusercontent.com/45205682/143872443-d6d124b0-0c8e-4035-8f9a-ee974a0b3625.png)

**Comment by MadsVSChristensen** [comment]
0.7.0 has just been release with a fix for this issue. 

Thanks for your kind words and input! It is very nice to hear :) 

What you suggest about open answer field, I dont quite see the image matching the description. The image seems to be a choice-question (RPChoiceAnswerFormat), but you description is about the (RPScaleAnswerFormat). 
If you are looking for the option to have a "free text"-option in a choice-question, then RPChoice has the parameter "isFreeText", which - if set to true - will give show like the one in the picture. 

To see how some of these things can be done - take a look at: https://carp.cachet.dk/creating-a-survey/

If I misunderstood, please feel free to create a new issue on this matter. 

Hope this helps, 
Mads

**Comment by eveetc** [comment]
Wow, I haven't seen that option!
Great, that solved my issue :) 
The updates are great!
