### ISSUE TITLE
go previous step missing

### ISSUE THREAD

**Issue by alexodus** [cph-cachet/research.package#6]
Hi,
with ResearchKit on iOS, the user can go to the previous step (with the selected response checked).

**Comment by barnabashomola** [comment]
Hi,
Sorry for the late answer. 

Yes, we know about that feature and working on it. 
Tasks which are not ordered are under development right now.
That will make branching available and also the participant will be able to navigate between questions.

**Comment by alexodus** [comment]
Wonderful!!! I saw in the branch _feature/navigable-ordered-task_  and your changes are almost OK!  :P Where is the CANCEL button? In this way I cannot interrupt the survey. In Android we have back button, but in iOS?

**Comment by barnabashomola** [comment]
We're glad you like it but don't forget that branch is still under development, it's not stable.

You can find the CANCEL button on the right hand side in the app bar with the 'X' symbol.

**Comment by alexodus** [comment]
> You can find the CANCEL button on the right hand side in the app bar with the 'X' symbol.
Ah, I cannot see it because it was blue like my title bar :P
![image](https://user-images.githubusercontent.com/2721510/75880082-e4dceb00-5e1c-11ea-8a8e-58f1ce296a3e.png)

**Comment by barnabashomola** [comment]
The icon button takes the `accentColor` from the `Theme` as of it now. If your `primaryColor` and `accentColor` happen to be the same it can happen...

**Comment by alexodus** [comment]
Ehm....ok, I'm sorry! :P
