### ISSUE TITLE
Add option to change textalignment in IntroductionSteps

### ISSUE THREAD

**Issue by eveetc** [cph-cachet/research.package#60]
For now all texts use block text standard, it would be great to change that, so texts dont have big gaps inbetween words.

**Comment by MadsVSChristensen** [comment]
Hi @eveetc,

I will add this for the upcoming release. Thanks for letting us know about the issue.

Mads

**Comment by eveetc** [comment]
> 

Thank you :)

**Comment by MadsVSChristensen** [comment]
After review we decided to go with `Alignment.start` instead. Having options for text alignment would only complicate RP for the users. Hope this is works with your issue as well.

**Comment by eveetc** [comment]
That's great :) thanks!
