### ISSUE TITLE
Version mismatch between pub.dev and main branch

### ISSUE THREAD

**Issue by matthiasn** [cph-cachet/research.package#61]
The latest published version is [0.6.7](https://pub.dev/packages/research_package/versions/0.6.7) while the latest version in the main branch is [0.6.6](https://github.com/cph-cachet/research.package/commit/21f3ba1e44c8e753fa5fc385ef088e546fff416a#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R3). I forked the lib earlier today and now I wonder if I have the latest version, or if there is anything that wasn't merged yet. Thanks!

**Comment by MadsVSChristensen** [comment]
Hi @matthiasn,

Thanks for noticing and letting us know! Apologies for the missed merge. With the upcoming release master will be brought in line as well. 

Mads
