### ISSUE TITLE
Skip this question not translated

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/research.package#68]
![skipthisquestion](https://user-images.githubusercontent.com/1552887/181272400-4e1b3a9d-b260-4639-86e8-e653c08a79c9.jpg)

The Skip this question is not being translated when localized to Danish

**Comment by MadsVSChristensen** [comment]
In the `da.json` file in your `assets` folder, you need to add a translation for that line. 
Here is an example. 

```
  "Skip this question": "Spring spørgsmålet over",
```

![Screenshot 2022-08-08 at 09 43 24](https://user-images.githubusercontent.com/37549483/183367724-30eae879-36d9-41c8-ac84-925e4bfa593b.png)

**Comment by MadsVSChristensen** [comment]
Closing the issue as the translation works as intended
