### ISSUE TITLE
Feature Request: optional "info/details page" on single Step

### ISSUE THREAD

**Issue by alexodus** [cph-cachet/research.package#7]
In researchkit we can implement the "info" page on single Step.

**Comment by barnabashomola** [comment]
Hi, 

Can you elaborate a little bit what you mean exactly by the "Info Page"?

Thank you!

**Comment by alexodus** [comment]
See here: https://www.youtube.com/watch?v=7vhkt1l2uoY
![image](https://user-images.githubusercontent.com/2721510/75886785-152a8680-5e29-11ea-901b-72b6184a8a34.png)

**Comment by MadsVSChristensen** [comment]
See RPInstructionStep
