### ISSUE TITLE
Is it possible to customise the Survey Complete image?

### ISSUE THREAD

**Issue by gerryau** [cph-cachet/research.package#70]
At the moment when a survey is completed it shows a blue checkmark as an image, is there anyway to customise this?

**Comment by MadsVSChristensen** [comment]
The latest version of Research Package has a new icon - have a look at it.

Using a `RPCompletionStep` will always have the same icon at the moment. Another option is to use the `RPInstructionStep` and use your own icon and text.

Best regards,
Mads
