### ISSUE TITLE
Missing Step Progress in AppBar Title

### ISSUE THREAD

**Issue by alexodus** [cph-cachet/research.package#8]
In 0.2.0 version the progress ("#current_step of #totals_step") in the AppBar title is missing. Why?

**Comment by MadsVSChristensen** [comment]
Hi @alexodus, thank you for your patience.

We implemented the navigation-feature as part of the previous release. As a result the number of questions has become dynamic. E.g. A questions like "Do you smoke?" can branch to further questions about smoking if the answer was "Yes". This means you could start at question "1 of 20" and after one question, be at "2 of 16" or "5 of 20".

A design choice was made to **not** show this, as it was no longer a good indicator for the users progress. 

Hope this helps!
Feel free to close the issue, if you find the answer satisfying.

**Comment by barnabashomola** [comment]
With the next version of Research Package the counter will be available for the OrderedTask, but not for the NavigableOrderedTask as @MadsVSChristensen mentioned before. 

On how to indicate the progress of the NavigableOrderedTask we'll have further design discussions. All feedback and suggestion is welcome of course!

**Comment by ezmegy** [comment]
Hey guys, 

Any updates on progress bars maybe? 

Is there anything in the pipeline or do you maybe have ideas on a workaround until then?

Cheers

**Comment by MadsVSChristensen** [comment]
The progress indicator is back for *RPOrderedTask* - however as progress during a RPNavigableTask is not linear, it will not appear.
