### ISSUE TITLE
Cognition Package lang files are the same as in Research Package

### ISSUE THREAD

**Issue by IgorMatias3** [cph-cachet/research.package#80]
Even though CP and RP work like that, it is now feasible to have all the translations for Cognition Package in the Research Package lang files.
This limitation originated from the RPLocations.

**Comment by bardram** [comment]
Another issues, is that the translation key for the cognition package are not real keys as such, but the full text. For example, 

```
"review_form": "Review this form below, and tap AGREE if you're ready to continue.",

  "Find the blue dots on the next screen. These are the targets dots.": "Find the blue dots on the next screen. These are the targets dots.",
```

where `review_form` is a real key, the other is a loooooooong text.
