### ISSUE TITLE
How to obtain single StepResults from TaskResults?

### ISSUE THREAD

**Issue by jb8991** [cph-cachet/research.package#81]
Hello,
i don't know if it is the right place here, but i am a bit lost when trying to retrieve Results from my Surveys created with RP. This is my task:

`class SurveyTaskRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RPUITask(
      task: linearSurveyTask,
      onSubmit: (RPTaskResult result) {
        resultCallback(result);
      },
      onCancel: (RPTaskResult? result) {
        print(result.toString() + ' --- canceled');
      },
    );
  }
}

void resultCallback(RPTaskResult result) {
  // Do anything with the result
  print(result.getStepResultForIdentifier('booleanQuestionStepID'));
  print(result.results);
}

RPOrderedTask linearSurveyTask = RPOrderedTask(
  identifier: "surveyTaskID",
  steps: [
    instructionStep,
    smokingQuestionStep,
    smokingQuestionStep2,
  ],
);
`
When finishing the task, the Callback-function just prints the Results as sepcified in RPResult .toString() method:
I/flutter ( 6079): RPStepResult - identifier: booleanQuestionStepID
I/flutter ( 6079): {booleanQuestionStepID: RPStepResult - identifier: booleanQuestionStepID, booleanQuestionStepID2: RPStepResult - identifier: booleanQuestionStepID2}

How can i retrieve the actual value of the answers?
Would be so glad if someone could help, thanks a lot.

**Comment by bardram** [comment]
When the `RPUITask` is submitted, the `onSubmit` method is called. In the above code, this function merely forwards the call to the `resultCallback` method. As stated in the comments, you can implement any logic here and handle the result, which is available in the `result` object. In this simple example, the result is merely printed to the console, but you can implement any logic you want here, like saving it to a database (via your persistence layer), or uploading it to a cloud backend (via your networking layer). 

I hope this helps.

**Comment by jb8991** [comment]
Thank you, but this doesn't answer my question. How do I get the actual answer the user gave when answering a question (i.e. the content of the QuestionStepResult, which would be "yes" or "no"). Right now I just get "RPStepResult - identifier: booleanQuestionStepID", but I need the actual answer. Thank you for your help!
