### ISSUE TITLE
Provide screenshots

### ISSUE THREAD

**Issue by James-A-White** [cph-cachet/research.package#9]
I'm quite interested in this package but see it has a low score due to the fact that it's not popular. Perhaps if you included screenshots in your documentation on pub.dev that would help improve the adoption of the package.

Feel free to close this issue as soon as you read it.  :-)

Thx!

**Comment by MadsVSChristensen** [comment]
Hi @James-A-White 

Thank you for the suggestion! 
We currently have a website /[https://www.researchpackage.org/]() which features all the documentation we provide. We agree this could be made clearer for potential users. Your suggestion will be considered with the next release!

I will keep this issue open until then.

**Comment by MadsVSChristensen** [comment]
https://www.researchpackage.org/ has been updated and includes screenshots.
